# Cloudflare Pages 설정
name = "fc-inventrix"
compatibility_date = "2025-01-17"

[site]
bucket = "./dist"  # 빌드된 정적 파일의 위치

[build]
command = "npm install && npm run build"  # 빌드 명령어

[env.production]
NODE_VERSION = "18"  # Node.js 버전 지정

# 필요한 헤더 설정
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

# SSR 설정
[functions]
directory = "./dist/functions"  # SSR 함수 디렉토리
