name = "my-solid-app" # 앱 이름
type = "javascript" # 앱 유형
workers_dev = true # Workers Dev 모드 활성화
compatibility_date = "2025-01-17" # 최신 날짜로 설정

[build]
command = "npm install && npm run build" # 빌드 명령어

[build.upload]
format = "modules" # Cloudflare Modules 포맷 사용
main = "./dist/index.js" # 진입점 파일 경로
